In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cpu


In [2]:
# Scaler
scaler = torch.tensor(7)
print(scaler)
print(scaler.ndim)
print(scaler.shape)

tensor(7)
0
torch.Size([])


In [3]:
vector = torch.tensor([1, 2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2])
1
torch.Size([2])


In [4]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [6]:
# Random tensor
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0359, 0.2363, 0.5984, 0.8403],
         [0.6762, 0.0967, 0.0625, 0.7149],
         [0.0506, 0.9202, 0.1231, 0.8083]]),
 torch.float32)

In [7]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [8]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [9]:
# Tensor from a range
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten, one_to_ten.shape, one_to_ten.ndim  

(tensor([0, 2, 4, 6, 8]), torch.Size([5]), 1)

In [10]:
# Creating tensors like
five_zeros = torch.zeros_like(input = one_to_ten)
five_zeros    

tensor([0, 0, 0, 0, 0])

### Common issues that we come across with pytorch

* Tensors not correct data type
* Tensors not right shape
* Tensors not on the right device

In [11]:
# Datatype

torch_flot32 = torch.tensor([1, 2, 3, 4, 6], dtype=torch.float32, device=None, requires_grad=False)
torch_flot32, torch_flot32.dtype, torch_flot32.device

(tensor([1., 2., 3., 4., 6.]), torch.float32, device(type='cpu'))

In [12]:
# Changing datatype
torch_flot16 = torch_flot32.type(torch.half)
torch_flot16 


tensor([1., 2., 3., 4., 6.], dtype=torch.float16)

In [13]:
torch_flot32 * torch_flot16 

tensor([ 1.,  4.,  9., 16., 36.])